<h1>Ekart Terms of Use</h1><br />
 
This document is an electronic record in terms of Information Technology Act, 2014 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2014. This electronic record is generated by a computer system and does not require any physical or digital signatures.


This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.ekart.com website.


The domain name www.ekart.com (hereinafter referred to as "Website") is owned by Ekart Internet Private Limited a company incorporated under theCompanies Act, 1956 with its registered office at Vaishnavi Summit, Ground Floor, 7th Main, 80 feet Road, 3rd Block, Koramangala Industrial Layout, Next to Wipro office, Corporation Ward No. 68, Koramangala, Bangalore - 560 034, Karnataka, India (hereinafter referred to as "Ekart").


Your use of the Website and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with Ekart Internet Private Limited and these terms and conditionsincluding the policies constitute Your binding obligations, with Ekart.


For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. Ekart allows the User to surf the Website or making purchases without registering on the Website. The term "We", "Us", "Our" shall mean Ekart Internet Private Limited.

